### ISSUE TITLE
Entity is not modifyable in HomeAssistant

### ISSUE THREAD

**Issue by Craftoncu** [Craftoncu/hacs-vikunja-integration#10]
### System Health details

-

### Checklist

- [X] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The embedded task list is not modifyable in home assistant:
![image](https://github.com/Craftoncu/hacs-vikunja-integration/assets/55136417/e7c484de-0f6f-4c68-a764-1df7c87f44bb)

### Reproduction steps

1. Install integration
2. Embed task list into view
3. Try to check a task to be done

### Debug logs

```text
-
```

### Diagnostics dump

-

**Comment by fernandeusto** [comment]
The same problem here. The list on HomeAssistant is not editable
![imagen](https://github.com/Craftoncu/hacs-vikunja-integration/assets/87156183/111bc49c-f23e-4e50-bda4-83508c27af78)


What permisions are needed to create token?
![imagen](https://github.com/Craftoncu/hacs-vikunja-integration/assets/87156183/397c01e6-1fb3-480d-babd-b9dd89a609f9)

**Comment by bannert1337** [comment]
I ticked all permissions and the lists are still not editable.

**Comment by Craftoncu** [comment]
Hey!
Aquawolf created a pull request for this issue. I will have a look at it in a few ours.
Then the issue may be fixed. Otherwise I will continue finding the error

**Comment by bannert1337** [comment]
I have looked at the source code and noticed that multiple parts are commented out. 
```python
class VikunjaTaskTodoListEntity(
    CoordinatorEntity[VikunjaDataUpdateCoordinator], TodoListEntity
):
    """A To-do List representation of the Shopping List."""

    _attr_has_entity_name = True
    _attr_supported_features = (
#        TodoListEntityFeature.CREATE_TODO_ITEM
         TodoListEntityFeature.UPDATE_TODO_ITEM
#        | TodoListEntityFeature.DELETE_TODO_ITEM
#        | TodoListEntityFeature.MOVE_TODO_ITEM
#        | TodoListEntityFeature.SET_DUE_DATE_ON_ITEM
#        | TodoListEntityFeature.SET_DESCRIPTION_ON_ITEM
    )

    def __init__(
        self,
        coordinator: VikunjaDataUpdateCoordinator,
        name: str,
        config_entry_id: str,
        project_id: str,
    ) -> None:
        """Initialize LocalTodoListEntity."""
        super().__init__(coordinator)
        self._attr_name = name.capitalize()
        self._attr_unique_id = f"{config_entry_id}-{project_id}"
        self._project_id = project_id

    @property
    def todo_items(self) -> list[TodoItem] | None:
        """Get the current set of To-do items."""
        if self.coordinator.data is None:
            return None
        return [_convert_api_item(item) for item in self.coordinator.data]

    async def async_update_todo_item(self, item: TodoItem) -> None:
        """Update a To-do item."""
        uid: str = cast(str, item.uid)
        await self.coordinator.client.update_task(
            self._project_id,
            uid,
            item.status == TodoItemStatus.COMPLETED,
        )
        await self.coordinator.async_refresh()

    # async def async_create_todo_item(self, item: TodoItem) -> None:
    #     """Add an item to the To-do list."""
    #     await self.coordinator.api.insert(
    #         self._project_id,
    #         task=_convert_todo_item(item),
    #     )
    #     await self.coordinator.async_refresh()

    # async def async_delete_todo_items(self, uids: list[str]) -> None:
    #     """Delete To-do items."""
    #     await self.coordinator.api.delete(self._task_list_id, uids)
    #     await self.coordinator.async_refresh()

    # async def async_move_todo_item(
    #     self, uid: str, previous_uid: str | None = None
    # ) -> None:
    #     """Re-order a To-do item."""
    #     await self.coordinator.api.move(self._task_list_id, uid, previous=previous_uid)
    #     await self.coordinator.async_refresh()

# def _order_tasks(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
#     """Order the task items response.

#     All tasks have an order amongst their sibblings based on position.
#         Home Assistant To-do items do not support the Google Task parent/sibbling
#     relationships and the desired behavior is for them to be filtered.
#     """
#     parents = [task for task in tasks if task.get("parent") is None]
#     parents.sort(key=lambda task: task["position"])
#     return parents
```

**Comment by Craftoncu** [comment]
Hey @bannert1337, its because the functionality is not implemented yet. And I just deactivated the code. But didnt want to delete it because of probably later implementation

**Comment by Craftoncu** [comment]
Current status is, that the entity is now modifiable but home assistant does not sync done/undone into the ui. I will have a look on that

**Comment by bannert1337** [comment]
Currently, it's not possible to add new tasks. Is there an ETA for this?

**Comment by Craftoncu** [comment]
Not directly, I'm on the sync issue atm. But I have a lot of work to do. So I would appreciate some help. And I never did that much with python. So it takes more time for me

**Comment by bannert1337** [comment]
I see. I haven't worked much with Python either, but I am willing to support you. I'll have a look later!

**Comment by Craftoncu** [comment]
I have found some code parts which may be the reason for the rest of the errors. But my devcontainer stopped working. So I will have a look tomorrow

**Comment by fernandeusto** [comment]
Now on 0.0.2 version:

- BUG SOLVED: it does not give an error when editing a value as checked or unchecked
- but it does not save the changes betwen checked or unchecked in the HA itself
- it no synchronize from Vikunja the checked elements. Read all elements as unchecked
- It also does not allow adding new to-do elements

**Comment by Craftoncu** [comment]
I know about this issue, but I haven't found time yet to fix my devcontainer. I get some permission errors for the setup script. Can anybody confirm this?

**Comment by Craftoncu** [comment]
I just fixed the issue. Go update to release v0.0.3! :D
